### ISSUE TITLE
A suggestion to add GENEA Challenge

### ISSUE THREAD

**Issue by Svito-zar** [wentaoL86/awesome-body-language#1]
Hello,

Thank you for this nice repository.

I have noticed that the only gesture generation challenges called GENEA Challenges are not on your list of Challenges:
https://genea-workshop.github.io/2020/#gesture-generation-challenge
https://genea-workshop.github.io/2022/challenge/
https://genea-workshop.github.io/2023/challenge/

Please consider adding it :)

**Comment by wentaoL86** [comment]
Thanks for your suggestion, we will consider setting up a section specially for these challenges.
